### ISSUE TITLE
need help getting click event to recognize

### ISSUE THREAD

**Issue by bigtone1284** [bigtone1284/rail_time#10]
@harimohanraj89 @htella @DrRobotmck,
I am adding Backbone to my app.  As I mentioned to Hari and Harish yesterday, I am trying to add a dropdown to the page with a listing of all stations on a given line AFTER a user has selected their line of interest.  

Right now, I have set up a view for the drop down, a view for each station in the drop down (with template), a collection for stations, a model for stations, and the App.initialize.

I have a click event on the three line names, but they do not register.  Not certain what dot I am not connecting in this scenario.  I will push my latest code.

**Comment by DrRobotmck** [comment]
what view should i look at?
