### ISSUE TITLE
debugger issues

### ISSUE THREAD

**Issue by bigtone1284** [bigtone1284/rail_time#13]
@htella @DrRobotmck @harimohanraj89 

Instructors,

Hope that you guys get home well before the fury of Juno.  I am garrisoned at home with my code and ample supply of coffee.  

I've been having an issue with 'debugger' pausing my js code even though I can't find any debugger lines in my repo.  The line that debugger is pausing on is line 18 in my updateView.js file.  Here is what the line looks like at current:

``` javascript
    renderUpdate: function(update) {
        var updateListing = new App.Views.UpdateListingView({ model: update });
        this.$("table tbody").append(updateListing.$el.children());
        this.renderSave();
    },
```

the line highlight is

``` javascript
var updateListing = new App.Views.UpdateListingView({ model: update });
```

App.Views.UpdateListingView looks like this:

``` javascript
App.Views.UpdateListingView = Backbone.View.extend({
    class: 'update-listing',
    initialize: function() {
        this.template = HandlebarsTemplates['updateListing'];
        this.render();
    },
    render: function() {
    this.$el.html(this.template(this.model.toJSON()));
  },
  events: {

  }  
});
```

I have tried refreshing, emptying the cache, deleting history, etc.  Any ideas?  Thanks.

**Comment by DrRobotmck** [comment]
Did you add any breakpoints thought the console in chrome? Take a look at your sources tab.

**Comment by bigtone1284** [comment]
@DrRobotmck @htella @harimohanraj89 

That was it.  Thanks.
