### ISSUE TITLE
write stop dictionary(hash) in js or Ruby

### ISSUE THREAD

**Issue by bigtone1284** [bigtone1284/rail_time#4]
@harimohanraj89 @htella @DrRobotmck ,

So here is a current issue I have....

Currently, I want to allow users to find the station they'd like to search upon, first by choosing which line and then by picking their station from only a listing of the stations on their line of interest.  

From this, I'd like to take their selection and return to them the API result (my api results are pretty constricting, it just returns the trains currently running and when they will arrive at a given station).  

Besides the dynamic API with real-time data, MTA has also given me their "static" api results, which consist of a group of .txt files that are accessible via a browser download.  

I am currently finishing parsing the text files from CSV to a more useful nested collection.

My question is, if I want the user experience to be dynamic (no page reloads ever!) can I have this "static" api return exist as a ruby file?  Or should it/must it be something I am accessing in my js?  Can I do this with a Ruby file and use a controller to accept this user input?, return the needed JSON to refresh the dom?

**Comment by harimohanraj89** [comment]
Closing after our conversation.
